# **Numpy**

In [1]:
import numpy as np # type: ignore # Used to import numpy as np to use its functions

In [2]:
nums = list(range(1, 25)) # Used to create a list
print("List : ", nums)
array = np.array(nums)
print(f"Array : {array}")
type(array)

List :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


numpy.ndarray

In [3]:
arr = np.array([1,2,3,4,5]) # Used to create a array
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.arange(1, 25) # Used to create a array with the given range
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [5]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) # Used to create a 2D array
arr3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]]) # Used to create 3D array
print(arr2.ndim) # Used to find the dimension of the array
print(arr3.ndim)
print(arr2)

2
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Creating a 3d Array (2 blocks, 3 rows, 4 columns)
arr = np.array([[[1,2,3,4], [5,6,7,8], [17,18,19,20]], [[9,10,11,12], [13,14,15,16], [21,22,23,24]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [13 14 15 16]
  [21 22 23 24]]]
3


In [7]:
arr4 = np.zeros((2,3)) # Used to create a 2D array with zeros
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr5 = np.linspace(1, 10, 5) # Used to create a array with the given range
arr6 = np.linspace(1,10,8).reshape(2,2,2) # Used to create a array with the given range in 3D array 
arr7 = np.linspace(1,10,4).reshape(2,2) # Used to create a array with the given range in 2D array
print("Dimension of arr6 : ",arr6.ndim)
print("Dimension of arr5 : ",arr5.ndim)
print("Dimension of arr7 : ",arr7.ndim)

Dimension of arr6 :  3
Dimension of arr5 :  1
Dimension of arr7 :  2


In [9]:
nums1 = np.arange(1,31).reshape(5,6) # Used to create a array with the given range and resape it in 5x6 matrix
print(nums1)
print(nums1.shape)  # Used to find the shape of the array
print(nums1.size) # Used to find the size of the array
print(nums1.dtype) # Used to find the data type of the array
print(nums1.T) # Used to transpose the array
print(nums1.ravel()) # Used to flatten the array
print(nums1.max()) # Used to find the maximum value of the array
print(nums1.min()) # Used to find the minimum value of the array
print(nums1.sum()) # Used to find the sum of the array
print(nums1.mean()) # Used to find the mean of the array
print(nums1.std()) # Used to find the standard deviation of the array.
print(nums1.argsort()) # Used to find the index of the array

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)
30
int64
[[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
30
1
465
15.5
8.65544144839919
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [10]:
arr = np.random.randint(1, 100, 10) # Used to create a random array with the given range
print(arr, "\n")
arr1 = np.random.randint(1, 100, (3,4)) # Used to create a random 2D array with the given range
print(arr1, "\n")
arr2 = np.random.randint(1, 100, (3,3,3)) # Used to create a random 3D array with the given range
print(arr2, "\n")

[21 90 80 97 11 82 98 34 41 87] 

[[93 19 69 67]
 [12 57 42 88]
 [21 11  1 51]] 

[[[80 19 52]
  [71 98 39]
  [85 25 57]]

 [[ 2 98 80]
  [19 47 60]
  [10 45 15]]

 [[73 61 66]
  [78  6 15]
  [99  3 76]]] 



In [11]:
arr = np.random.random((10,5))
print(arr)

[[0.43355742 0.54683136 0.78354531 0.70422333 0.86969519]
 [0.35044881 0.26935089 0.28518296 0.60864388 0.12337849]
 [0.79714626 0.00788398 0.43530447 0.15385964 0.0921335 ]
 [0.18153152 0.60505332 0.67728091 0.19816388 0.38711946]
 [0.3000215  0.0622905  0.62549413 0.77293861 0.1046133 ]
 [0.62540639 0.5468423  0.70646346 0.16586779 0.36384534]
 [0.2347733  0.43490533 0.54609062 0.02415622 0.67130225]
 [0.90962269 0.1437087  0.400012   0.53438735 0.39897792]
 [0.56553911 0.08414211 0.37799235 0.17938147 0.79091243]
 [0.41913221 0.41980952 0.76485873 0.38691854 0.85882761]]
