# **Array vs List**

In [1]:
import numpy as np # type: ignore

In [2]:
nums = [1, 2, 3, 4, 5]
arr = np.array(nums)
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [3]:
arr5 = np.linspace(1, 10, 5)
print(arr5)

[ 1.    3.25  5.5   7.75 10.  ]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
nums = arr.reshape(2,3)
print(nums)


[[1 2 3]
 [4 5 6]]


In [5]:
nums = np.random.randint(1,5,9)
print(type(nums))

<class 'numpy.ndarray'>


In [6]:
arr = np.arange(10)
print(arr)
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1


In [7]:
arr = np.random.randint(1,10,(3,2))
nums = arr.flatten() # Converts 2d array to 1d
print(arr)
print(nums)


[[2 2]
 [4 9]
 [6 8]]
[2 2 4 9 6 8]


In [8]:
arr = [[1, 2, 3],[4 ,5 ,6],[7, 8, 9]]
nums = np.array(arr)
print("List : ",arr)
print("Array : ",nums)

List :  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
arr = np.random.randint(1, 5, (2, 3))
nums = arr.T
print(arr.shape)
print(nums.shape)

(2, 3)
(3, 2)


In [10]:
arr = np.arange(10)
print(arr)
print(arr[8])


[0 1 2 3 4 5 6 7 8 9]
8


In [11]:
arr = np.arange(10)
nums = arr[3:20:2] # Slicing the array [From : To : Gap]

print(nums)

[3 5 7 9]


In [12]:
arr = np.random.randint(1, 5, (6, 6))
print(arr)
nums = arr[0:6,1:2] # [0:6] includes all 6 rows and[1:2] includes 1 and 3 columns
print(nums)

[[4 1 3 1 1 3]
 [3 1 2 3 3 2]
 [4 1 2 1 2 3]
 [1 3 1 4 1 2]
 [3 4 2 1 4 3]
 [2 2 1 1 3 3]]
[[1]
 [1]
 [1]
 [3]
 [4]
 [2]]


In [13]:
arr = np.arange(10)
nums = np.arange(10)
print(arr)
print(nums)
print("Sum : ", arr + nums)
print("Product : ", arr * nums)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
Sum :  [ 0  2  4  6  8 10 12 14 16 18]
Product :  [ 0  1  4  9 16 25 36 49 64 81]


In [14]:
x = [1, 2, 3, 4, 5]
y = [6, 7, 8, 9, 10]
print("Addition of Lists",x + y) 
# Multiplication of Lists is not supported
x = np.array(x)
y = np.array(y)
print("Addition of Array : ", x + y)
print("Multiplication of Array : ",x * y)

Addition of Lists [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Addition of Array :  [ 7  9 11 13 15]
Multiplication of Array :  [ 6 14 24 36 50]
